describe('e2e - currency exchange', () => {
    it ('login to the application', () => {
        browser.url('http://zero.webappsecurity.com/index.html')
        const signin = $('#signin_button')
        signin.waitForExist()
        signin.click()
        const username = $('#user_login')
        username.waitForExist()
        username.setValue('username')
        const password = $('#user_password')
        password.setValue('password')
        const submit = $('input[type="submit"]')
        submit.click()
        $('.nav-tabs').waitForExist()
    })

    it ('shd make currency exchange', () => {
        $('#pay_bills_tab').waitForExist()
        $('#pay_bills_tab').click()
        $('#tabs > ul > li:nth-child(3) > a').click()
        const currency = $('#pc_currency')
        currency.selectByAttribute('value', 'CAD')
        $('#pc_amount').setValue('500')
        $('#pc_inDollars_true').click()
        $('#purchase_cash').click()
        const successMsg = $('#alert_content')
        expect(successMsg).toHaveText('Foreign currency cash was successfully purchased.')
    })
})